# Generated by Django 4.2 on 2023-04-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_id',
            new_name='room',
        ),
    ]
