# Generated by Django 4.2 on 2023-04-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_room_id_reservation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
    ]
