# Generated by Django 4.2 on 2023-04-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.room'),
            preserve_default=False,
        ),
    ]
